### ISSUE TITLE
Fatal error during tests

### ISSUE THREAD

**Issue by alucryd** [matteodisabatino/express-prometheus-middleware#2] opened 2023-09-20 10:01 UTC
Hi there, I'm trying to replace prometheus-api-metrics with this, however I'm getting an error when running `yarn test`, which does not happen with prometheus-api-metrics. Do you have any idea what could be causing this?

I'm using node 18.18.0 on Arch Linux.

```
FATAL ERROR: HandleScope::HandleScope Entering the V8 API without proper locking in place
1: 0x55ea79e16ec5 node::Abort() [/usr/bin/node]
 2: 0x55ea79c8dff1 node::OnFatalError(char const*, char const*) [/usr/bin/node]
 3: 0x55ea7a01a23f v8::Utils::ReportApiFailure(char const*, char const*) [/usr/bin/node]
 4: 0x55ea7a01b471 v8::HandleScope::Initialize(v8::Isolate*) [/usr/bin/node]
 5: 0x55ea79d404dc node::InternalCallbackScope::InternalCallbackScope(node::Environment*, v8::Local<v8::Object>, node::async_context const&, int) [/usr/bin/node]
 6: 0x55ea79d40f23 node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/usr/bin/node]
 7: 0x55ea79d41178 node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/usr/bin/node]
 8: 0x7fc48215922d  [/home/alucryd/Projects/customers-api/node_modules/@matteodisabatino/gc_info/build/Release/gc_info.node]
 9: 0x7fc4828aa9fb  [/usr/lib/libuv.so.1]
10: 0x7fc4828c7cdb  [/usr/lib/libuv.so.1]
11: 0x7fc4828aff9f uv_run [/usr/lib/libuv.so.1]
12: 0x55ea79d41e2a node::SpinEventLoop(node::Environment*) [/usr/bin/node]
13: 0x55ea79e63c5d node::NodeMainInstance::Run(int*, node::Environment*) [/usr/bin/node]
14: 0x55ea79e6412e node::NodeMainInstance::Run() [/usr/bin/node]
15: 0x55ea79dcba7c node::LoadSnapshotDataAndRun(node::SnapshotData const**, node::InitializationResult const*) [/usr/bin/node]
16: 0x55ea79dd0715 node::Start(int, char**) [/usr/bin/node]
17: 0x7fc481227cd0  [/usr/lib/libc.so.6]
18: 0x7fc481227d8a __libc_start_main [/usr/lib/libc.so.6]
19: 0x55ea79d3e5c5 _start [/usr/bin/node]
```

**Comment by matteodisabatino** [comment] 2023-09-20 10:32
Hi, the error seems to be caused by gc_info which is another module of mine and it's a dependency of express-prometheus-middleware.

Probably, there is a mismatch between your libuv version and the one I used to compile gc_info. I'm not sure but I suppose this is the more realistic hypothesis because I use this module in Alpine and Debian (via Docker) and I never encountered this error.

Anyway, it's very strange: I compile gc_info using nan and prebuild in order to avoid these kind of problems.

Another possibility is there is a bug in node 18.18.0 (it was released just two days ago). Could you please try to downgrade to node 18.17.1? This is the version I use.

**Comment by alucryd** [comment] 2023-09-20 12:09
Thanks for the quick reply, I tried earlier with 18.17.1 as well but I got the same result. I'm on arch linux, we have libuv 1.46.0. Maybe I can install from git so gc_info gets recompiled on my machine.

**Comment by matteodisabatino** [comment] 2023-09-20 12:29
Yeah, great idea. Let me know how can I help you.

**Comment by matteodisabatino** [comment] 2023-09-26 10:01
Hi @alucryd any news on that?

**Comment by matteodisabatino** [comment] 2023-11-02 09:48
Closing since no news provided

**Closed as completed by matteodisabatino** 2023-11-02 09:48 UTC
